name: Publish Java snapshot

on:
  workflow_dispatch:

jobs:
  build_linux:
    name: Linux x64 build
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Install arm64 toolchain
        run: sudo apt install -y g++-aarch64-linux-gnu
      - name: Setup CMake
        uses: lukka/get-cmake@latest
      - name: Build box2d-jni
        run: ./gradlew :box2d-jni-natives-linux:buildNativeLibLinux :box2d-jni:build
        working-directory: box2d-jni/

      - name: Upload native lib artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-libs
          path: box2d-jni/box2d-jni-natives-linux/build/libs/*.jar
          compression-level: 0

  build_linux_arm64:
    name: Linux arm64 build
    runs-on: ubuntu-22.04-arm

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup CMake
        uses: lukka/get-cmake@latest
      - name: Build box2d-jni
        run: ./gradlew :box2d-jni-natives-linux-arm64:buildNativeLibLinuxArm64 :box2d-jni-natives-linux-arm64:build :box2d-jni:build
        working-directory: box2d-jni/

      - name: Upload native lib artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-libs-arm64
          path: box2d-jni/box2d-jni-natives-linux-arm64/build/libs/*.jar
          compression-level: 0

  build_windows:
    name: Windows build
    runs-on: windows-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup CMake
        uses: lukka/get-cmake@latest
      - name: Build box2d-jni
        run: ./gradlew :box2d-jni-natives-windows:buildNativeLibWindows :box2d-jni-natives-windows-arm64:buildNativeLibWindowsArm64 :box2d-jni:build
        working-directory: box2d-jni/

      - name: Upload native lib artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-libs
          path: |
            box2d-jni/box2d-jni-natives-windows/build/libs/*.jar
            box2d-jni/box2d-jni-natives-windows-arm64/build/libs/*.jar
          compression-level: 0

  build_macos:
    name: macOS build (and Android)
    runs-on: macos-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Install coreutils
        run: brew install coreutils
      - name: Setup CMake
        uses: lukka/get-cmake@latest
      - name: Build box2d-jni
        run: ./gradlew :box2d-jni-natives-macos-arm64:buildNativeLibMacosArm64 :box2d-jni-natives-macos:buildNativeLibMacos build
        working-directory: box2d-jni/

      - name: Upload MacOS lib artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-libs
          path: |
            box2d-jni/box2d-jni-natives-macos/build/libs/*.jar
            box2d-jni/box2d-jni-natives-macos-arm64/build/libs/*.jar
          compression-level: 0

  publish:
    name: Build and publish Java and Android libs
    runs-on: ubuntu-latest
    needs: [ build_linux, build_linux_arm64, build_windows, build_macos ]
    environment: publish

    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Download native lib artifacts
        uses: actions/download-artifact@v4
      - name: Copy downloaded artifacts to resources
        run: |
          cp -r linux-libs/* .
          cp -r linux-libs-arm64/* .
          cp -r macos-libs/* .
          cp -r windows-libs/* .
      - name: Build and publish bindings
        run: ./gradlew build publishToMavenCentral
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_PASSWORD }}